### ISSUE TITLE
Docker Compose file version '2' support

### ISSUE THREAD

**Issue by chiehwu1989** [mesos/docker-compose-executor#10]
From the official Docker's web page, it states "Version 1 is supported by Compose up to 1.6.x. It will be deprecated in a future Compose release." [Link to the page](https://docs.docker.com/compose/compose-file/#versioning)

Is there a plan of supporting version '2' in the near future?

**Comment by gtejasvarma** [comment]
WIP should be available by end of next week.

**Comment by chiehwu1989** [comment]
That's great!
Can't wait to see it. Thx.

**Comment by kurtkopchik** [comment]
Me too! Any update on when the version '2' support will be ready?

**Comment by mbdas** [comment]
It would be updated in a day.

**Comment by mbdas** [comment]
Code pushed. Please verify and comment.

**Comment by mbdas** [comment]
Any feedback? Otherwise we can close this and open specific issues.
