### ISSUE TITLE
Jar version is hardcoded - should be parameterized

### ISSUE THREAD

**Issue by hcavalle** [mesos/docker-compose-executor#15]
In the bootstrap scripts used to provision via `vagrant up` the version required of the target compiled jar artifact is hard-coded. This should be parameterized via mvn to get the current version of the pom at the time `vagrant up` is run.

**Comment by mbdas** [comment]
We will address it asap. We are updating docs, delivering enhanced features, upgrading vagrant setup. By end of the month we will cut a new release.

**Comment by hcavalle** [comment]
Awesome, thanks for quick turnaround on the PR!
