### ISSUE TITLE
Integration with Running Mesos/Marathon

### ISSUE THREAD

**Issue by akamalov** [mesos/docker-compose-executor#8]
Greetings,

Thanks for the project! Wondering, how one would go integrating docker-compose executor with already running Mesos/Marathon ecosystem ?

Thanks,

Alex

**Comment by mbdas** [comment]
https://github.com/mesos/docker-compose-executor/blob/master/docs/dev-build.md

In existing mesos cluster, you need to install the compose executor and other components like docker daemon etc in mesos slave/agent nodes.

After that you just start issuing marathon requests specifying the executor.

Marathon and mesos master nodes does not need to change.

**Comment by akamalov** [comment]
Thanks a ton. Currently I am running full blown mesos/marathon env. Will be building docker-compose-executor next. Thanks so much.

Alex
